### ISSUE TITLE
redisBusDriver should accept the same new Redis() instance as redisDriver

### ISSUE THREAD

**Issue by thevolcanomanishere** [Julien-R44/bentocache#11]
For the service that I am using now, the only working way to connect to redis on a local private ipv6 network is by doing `new Redis()` and passing that to connection. I cannot get the same to work for redisBusDriver. Doing `redisConnection.options` satisfies typescript, but in the logs, I can see that none of the connection options are getting passed through

![Screenshot 2024-03-05 at 17 12 48](https://github.com/Julien-R44/bentocache/assets/9613565/c51cd23d-9858-47fc-a793-aff670848da0)

This removes the typescript error, but the connection stills fails and defaults to 127.0.0.1
![Screenshot 2024-03-05 at 17 13 00](https://github.com/Julien-R44/bentocache/assets/9613565/4eb6ad56-9186-4867-be2e-e2b9e5cfc2f1)

**Comment by Julien-R44** [comment]
hey!

actually this is done on purpose. The `redisBusDriver` uses the ioredis pub/sub feature. and to use the pub/sub we need two different instances of ioredis. See : https://github.com/redis/ioredis#pubsub

> It's worth noticing that a connection (aka a Redis instance) can't play both roles at the same time. More specifically, when a client issues subscribe() or psubscribe(), it enters the "subscriber" mode. From that point, only commands that modify the subscription set are valid. Namely, they are: subscribe, psubscribe, unsubscribe, punsubscribe, ping, and quit. When the subscription set is empty (via unsubscribe/punsubscribe), the connection is put back into the regular mode.

So that's why the `redisBusDriver` only accepts options and not an instance of ioredis. bentocache will create both instances for you

Let me know if that makes sense

**Comment by thevolcanomanishere** [comment]
I am creating a new RedisOptions object and passing that to redisBusDriver. I am logging out that RedisOptions object to double check that the env var is being injected and the correct parts extracted but there is still a connection issue. The logs show that its 127.0.0.1 attempting to connect instead of the provided host.

Note: I have to use family: 0 because I have to use ipv6 to communicate from this service to Redis

![Screenshot 2024-03-06 at 12 10 47](https://github.com/Julien-R44/bentocache/assets/9613565/4d4f3799-0e2a-4fc9-a6c4-4e5bd3d68ab1)

![Screenshot 2024-03-06 at 12 04 19](https://github.com/Julien-R44/bentocache/assets/9613565/0b97f7c8-8fab-4be0-b2f9-94aa58f70592)

**Comment by thevolcanomanishere** [comment]
I am now creating a new RedisOptions object and logging that to the console to double check that it is correct. You can see that it is failing to connect AND the host is 127.0.0.1 instead of the provided host. I checked the bentocache code, and all the bus driver does is pass that connection (RedisOptions) object to ioredis to make an instance.

Note: I have to use family: 0 because I have to connect to redis via ipv6 network

![Screenshot 2024-03-06 at 12 04 19](https://github.com/Julien-R44/bentocache/assets/9613565/788c2c66-3e3a-4228-a696-eb33a50b5b2a)

![Screenshot 2024-03-06 at 12 14 08](https://github.com/Julien-R44/bentocache/assets/9613565/e032cd04-5499-4cca-8391-6c61c43aaf27)

**Comment by thevolcanomanishere** [comment]
I created a stripped down version of this and ran it locally against redis and keydb just incase this was redis specific. It turns out that pub/sub does not want to connect over IPv6. You can try this yourself by running redis server with the bind command set to ::1 and using the same for the host setting

**Comment by Julien-R44** [comment]
wouldn't that be more of a configuration problem than anything else? Have you tried connecting via `ioredis` rather than bentocache? Does it work?

to see if the problem is on bentocache or ioredis side

**Comment by Julien-R44** [comment]
Published with bentocache@1.0.0-beta.8

**Comment by thevolcanomanishere** [comment]
@Julien-R44 Thank you very much for fixing this issue. I am sorry I missed your reply RE: trying with ioredis etc. Yes, I tested without bentocache using ioredis directly. I will try out the latest version and see if that fixes things 😎

**Comment by Julien-R44** [comment]
I think we've already got it in the docs: if not, happy to accept a PR! Thanksss
