### ISSUE TITLE
Binary encoding in RedisTransport can crash due to unsafe utf-8 conversion

### ISSUE THREAD

**Issue by gkachru** [Julien-R44/bentocache#19]
## Problem
1. @boringnode/bus uses the "message" event from ioredis. [see here](https://github.com/boringnode/bus/blob/d3782ab73df53b9963b8afc082be895bb497b4a2/src/transports/redis.ts#L72)
2. ioredis converts the binary buffer to utf-8 while sending the message to this event. [see here](https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/lib/DataHandler.ts#L125)
3. bentocache's BinaryEncoder decode function assumes the data in coming in binary. [see here](https://github.com/Julien-R44/bentocache/blob/1822312adfd58e8f71f69511572bb295ad8d52f5/packages/bentocache/src/bus/encoders/binary_encoder.ts#L91)

## How to replicate
You can replicate by setting a key with unicode value > 255. Add 'Ā' to the list of keys in the "binary encoding/decoding should works fine" test and it should crash.

### Possibly related ioredis issue
[support for binary subscriptions: pbsubscribe, pmessageBuffer and utf8 issues](https://github.com/redis/ioredis/issues/1825)

## Possible Solutions
1.  bentocache's BinaryEncoder encode function can `return buffer.toString('base64')` and then the decode function can use `const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data, 'base64')`. This way, the data is utf-8 safe.
2. bentocache can simply not use the BinaryEncoder and use the default JSONEncoder in RedisTransport.
3. @boringnode/bus can use the "messageBuffer" event from ioredis. This does not appear to convert the message to utf-8. [see here](https://github.com/redis/ioredis/blob/ec42c82ceab1957db00c5175dfe37348f1856a93/lib/DataHandler.ts#L131)

**Comment by Julien-R44** [comment]
Fixed and released with bentocache@1.0.0-beta.9. Feel free to re-open if issue persist

Thanks for the detailled issue!
