### ISSUE TITLE
Distributed locks

### ISSUE THREAD

**Issue by niksy** [Julien-R44/bentocache#2]
In cache stampede prevention section, you mention that locks are created in-memory. Are there any plans for [distributed locks such as those for Redis](https://redis.io/docs/manual/patterns/distributed-locks/)?

**Comment by Julien-R44** [comment]
In case you missed it, I wrote something about it here: https://bentocache.julr.dev/docs/stampede-protection#multi-instance-applications

For now, I'm convinced that adding distributed locks isn't worth the complexity, at least for bentocache v1. We may come back to this later, but for now, yeah, i'm not convinced it's worth it

**Comment by niksy** [comment]
Got it, thanks!
