### ISSUE TITLE
Question: DynamoDB support for TTL feature

### ISSUE THREAD

**Issue by bml1g12** [Julien-R44/bentocache#35]
This looks like a fantastic library! I just had a query, as considering using it with AWS Lambda to cache to DynamoDB.

I see from the documentation a `ttl` is supported for DynamoDB driver, but it doesn't mention enabling AWS' `TimeToLiveSpecification` when creating the DynamoDB resource in AWS, so I suppose that the current TTL functionality does not use the AWS' feature https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html for automatically deleting expired items, is that correct?

I wonder does bentocache clean up old keys in this case? i.e. If I regularly use new keys (e.g. the key including current date) - will the number of keys stored in DynamoDB infinitely increase over time (and thus the cost will increase linearly over time?). 

If it does support AWS' ttl (i.e. a fixed attribute with ttl timestamp) , it would be useful to specify that attribute name in the docs for DynamoDB setup

**Comment by Julien-R44** [comment]
Hey! Thanks for the issue :) 

Indeed, it was an oversight. TTLs on DynamoDB are supported and even recommended, because otherwise, as you mentioned, DynamoDB will keep growing indefinitely.

Added to the documentation with the above commit
