### ISSUE TITLE
Adaptative caching

### ISSUE THREAD

**Issue by Julien-R44** [Julien-R44/bentocache#8]
Sometimes, we don't know in advance how long the TTL has to be set. typically, when you call an API to get a token, and the API returns the token + its lifetime. It would be cool to be able to have a TTL equivalent to the duration of the token. for that, we could have a system like the following :

```ts
bento.getOrSet('token', (options) => {
	const result = await getTokenFromApi()
	options.ttl = result.tokenDuration
	return result
})
```

Just an example. Probably need to think more about the API

**Comment by ndragun92** [comment]
Sounds like a good plan.
What about tokens that can be revoked manually in that case?

**Comment by Julien-R44** [comment]
yup! in this case, you will have to invalidate your key yourself with `bento.delete('token')`
